# Generated by Django 2.2.4 on 2019-08-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcode',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='subjectcode',
            name='choice_five',
        ),
        migrations.RemoveField(
            model_name='subjectcode',
            name='choice_four',
        ),
        migrations.RemoveField(
            model_name='subjectcode',
            name='choice_one',
        ),
        migrations.RemoveField(
            model_name='subjectcode',
            name='choice_three',
        ),
        migrations.RemoveField(
            model_name='subjectcode',
            name='choice_two',
        ),
        migrations.RemoveField(
            model_name='subjectcode',
            name='question',
        ),
    ]
