# Generated by Django 2.2.4 on 2019-08-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190807_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
