# Generated by Django 2.2.4 on 2019-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_quiz_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='code',
        ),
        migrations.AddField(
            model_name='quiz',
            name='scode',
            field=models.CharField(default='lr10CBSE', max_length=120),
        ),
    ]
