# Generated by Django 2.2.4 on 2019-08-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190807_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='scode',
        ),
    ]
