# Generated by Django 2.2.4 on 2019-08-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_remove_quiz_scode'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformclass',
            name='mode',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
