# Generated by Django 2.2.4 on 2019-08-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_applicationformclass_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformclass',
            name='mode',
        ),
    ]
