# Generated by Django 2.2.4 on 2019-08-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_applicationformclass_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformclass',
            name='status',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
