# Generated by Django 2.2.4 on 2019-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_applicationformclass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregister',
            name='access',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
