# Generated by Django 2.2.4 on 2019-08-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_adminregister_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=64)),
                ('option1', models.CharField(max_length=64)),
                ('option2', models.CharField(max_length=64)),
                ('option3', models.CharField(max_length=64)),
                ('option4', models.CharField(max_length=64)),
                ('answer', models.CharField(max_length=64)),
                ('examcode', models.CharField(max_length=64)),
                ('subcode', models.CharField(max_length=64)),
            ],
        ),
    ]
