# Generated by Django 2.2.4 on 2019-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('option1', models.ImageField(upload_to='images1/')),
                ('option2', models.ImageField(upload_to='images1/')),
                ('option3', models.ImageField(upload_to='images1/')),
                ('option4', models.ImageField(upload_to='images1/')),
                ('examcode', models.CharField(max_length=64)),
                ('subcode', models.CharField(max_length=64)),
            ],
        ),
    ]
