# Generated by Django 2.2.4 on 2019-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='answer',
            field=models.ImageField(default=2, upload_to='images1/'),
            preserve_default=False,
        ),
    ]
